version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.88.2
    - 1.89.0
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
    - 1.93.1
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: stripe-rails
    versions:
    - 2.2.1
  - dependency-name: devise_token_auth
    versions:
    - 1.1.4
